from geoserver.catalog import Catalog

cat = Catalog('http://localhost:8080/geoserver/rest', '{{ gs_admin_user }}', '{{ gs_admin_password }}')
ds = cat.create_datastore('{{ app_name }}','geonode')
ds.connection_parameters.update(host='localhost', port='5432', database='{{ db_data_instance }}', user='{{ db_user }}', passwd='{{ db_password }}', dbtype='postgis', schema='public')
try:
    cat.save(ds)
except Exception as e:
    print e

